# SF Salaries Exercise 

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

** Import pandas as pd.**

In [48]:
import pandas as pd
import numpy as np

** Read Salaries.csv as a dataframe called sal.**

In [4]:
sal = pd.read_csv("../Data/Salaries.csv")

** Check the head of the DataFrame. **

In [5]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

** Use the .info() method to find out how many entries there are.**

In [6]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
Id                  148654 non-null int64
EmployeeName        148654 non-null object
JobTitle            148654 non-null object
BasePay             148045 non-null float64
OvertimePay         148650 non-null float64
OtherPay            148650 non-null float64
Benefits            112491 non-null float64
TotalPay            148654 non-null float64
TotalPayBenefits    148654 non-null float64
Year                148654 non-null int64
Notes               0 non-null float64
Agency              148654 non-null object
Status              0 non-null float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
Id                  148654 non-null int64
EmployeeName        148654 non-null object
JobTitle            148654 non-null object
BasePay             148045 non-null float64
OvertimePay         148650 non-null float64
OtherPay            148650 non-null float64
Benefits            112491 non-null float64
TotalPay            148654 non-null float64
TotalPayBenefits    148654 non-null float64
Year                148654 non-null int64
Notes               0 non-null float64
Agency              148654 non-null object
Status              0 non-null float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

**What is the average BasePay ?**

In [7]:
sal["BasePay"].head()

0    167411.18
1    155966.02
2    212739.13
3     77916.00
4    134401.60
Name: BasePay, dtype: float64

In [8]:
sal["BasePay"].mean()

66325.44884050643

66325.44884050643

** What is the highest amount of OvertimePay in the dataset ? **

In [9]:
sal["OvertimePay"].max()

245131.88

245131.88

** What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll). **

In [14]:
sal[sal["EmployeeName"]=="JOSEPH DRISCOLL"]["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

** How much does JOSEPH DRISCOLL make (including benefits)? **

In [15]:
sal[sal["EmployeeName"]=="JOSEPH DRISCOLL"]["TotalPay"]

24    270324.91
Name: TotalPay, dtype: float64

24    270324.91
Name: TotalPayBenefits, dtype: float64

** What is the name of highest paid person (including benefits)?**

In [32]:
sal["TotalPay"].max()

567595.43

In [39]:
sal[sal["TotalPay"]==sal["TotalPay"].max()]["EmployeeName"]

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

** What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [55]:
sal[sal["TotalPay"]==sal["TotalPay"].min()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [44]:
sal[sal["TotalPay"]==sal["TotalPay"].min()]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

** What was the average (mean) BasePay of all employees per year? (2011-2014) ? **

In [57]:
sal["BasePay"].mean()

66325.44884050643

In [62]:
salYear = sal.groupby("Year")

In [67]:
salYear["BasePay"].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

** How many unique job titles are there? **

In [69]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
Id                  148654 non-null int64
EmployeeName        148654 non-null object
JobTitle            148654 non-null object
BasePay             148045 non-null float64
OvertimePay         148650 non-null float64
OtherPay            148650 non-null float64
Benefits            112491 non-null float64
TotalPay            148654 non-null float64
TotalPayBenefits    148654 non-null float64
Year                148654 non-null int64
Notes               0 non-null float64
Agency              148654 non-null object
Status              0 non-null float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

In [70]:
sal["JobTitle"].count()

148654

In [89]:
salJT = sal.groupby(["JobTitle"])

In [128]:
sal.groupby(["JobTitle"]).size().max()

7036

In [81]:
salJT.sum().count()

Id                  2159
BasePay             2159
OvertimePay         2159
OtherPay            2159
Benefits            2159
TotalPay            2159
TotalPayBenefits    2159
Year                2159
Notes               2159
Status              2159
dtype: int64

In [80]:
salJT.sum()

,Id,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Status
JobTitle,,,,,,,,,,
ACCOUNT CLERK,2135990,3593966.94,30975.67,30017.53,0.00,3654960.14,3654960.14,166913,0.0,0.0
ACCOUNTANT,120796,233215.86,0.00,3930.48,0.00,237146.34,237146.34,10055,0.0,0.0
ACCOUNTANT INTERN,1350184,1379167.87,1172.67,13183.12,0.00,1393523.66,1393523.66,96528,0.0,0.0
"ACPO,JuvP, Juv Prob (SFERS)",135284,62290.78,0.00,0.00,17975.59,62290.78,80266.37,2014,0.0,0.0
ACUPUNCTURIST,18379,66374.40,0.00,1220.00,0.00,67594.40,67594.40,2011,0.0,0.0
ADMINISTRATIVE ANALYST,1771924,5899513.46,0.00,48289.22,0.00,5947802.68,5947802.68,187023,0.0,0.0
ADMINISTRATIVE ANALYST II,41084,118747.42,0.00,4246.65,0.00,122994.07,122994.07,4022,0.0,0.0
ADMINISTRATIVE ANALYST III,22041,185397.03,0.00,0.00,0.00,185397.03,185397.03,4022,0.0,0.0
ADMINISTRATIVE ENGINEER,47818,1209131.61,0.00,70482.69,0.00,1279614.30,1279614.30,20110,0.0,0.0
ADMINISTRATIVE SERVICES MANAGER,47331,226665.10,0.00,4381.64,0.00,231046.74,231046.74,6033,0.0,0.0
"ADMINISTRATOR, SFGH MEDICAL CENTER",37,245124.44,0.00,12000.00,0.00,257124.44,257124.44,2011,0.0,0.0
AFFIRMATIVE ACTION SPECIALIST,104063,409063.90,0.00,220.00,0.00,409283.90,409283.90,12066,0.0,0.0
AGRICULTURAL INSPECTOR,46773,106548.20,0.00,624.00,0.00,107172.20,107172.20,4022,0.0,0.0
"AIRPORT ASSISTANT DEPUTY DIRECTOR, BUSINESS ADMINI",34812,1927.50,0.00,0.00,0.00,1927.50,1927.50,2011,0.0,0.0
"AIRPORT ASSISTANT DEPUTY DIRECTOR, OPERATIONS",30201,15420.00,0.00,0.00,0.00,15420.00,15420.00,2011,0.0,0.0
AIRPORT COMMUNICATIONS OPERATOR,389192,1826364.85,273413.88,93021.13,0.00,2192799.86,2192799.86,54297,0.0,0.0
AIRPORT COMMUNICATIONS SUPERVISOR,24437,173171.65,510.27,2678.08,0.00,176360.00,176360.00,4022,0.0,0.0
AIRPORT ECONOMIC PLANNER,102945,1405892.68,0.00,1550.00,0.00,1407442.68,1407442.68,26143,0.0,0.0
AIRPORT ELECTRICIAN,133422,1623307.42,126702.41,98023.25,0.00,1848033.08,1848033.08,34187,0.0,0.0
AIRPORT ELECTRICIAN SUPERVISOR,12626,208407.45,5702.27,20067.80,0.00,234177.52,234177.52,4022,0.0,0.0
AIRPORT EMERGENCY PLANNING COORDINATOR,32064,151731.87,0.00,0.00,0.00,151731.87,151731.87,4022,0.0,0.0
AIRPORT MECHANICAL MAINTENANCE SUPERVISOR,4377,118978.52,0.00,9555.65,0.00,128534.17,128534.17,2011,0.0,0.0
AIRPORT NOISE ABATEMENT SPECIALIST,47378,98217.45,0.00,777.00,0.00,98994.45,98994.45,4022,0.0,0.0
AIRPORT OPERATIONS SUPERVISOR,128667,1017128.06,71408.13,50431.57,0.00,1138967.76,1138967.76,24132,0.0,0.0
AIRPORT POLICE SERVICES AIDE,3848510,9570424.91,1024561.05,649311.19,0.00,11244297.15,11244297.15,376057,0.0,0.0
AIRPORT PROPERTY SPECIALIST I,197341,994914.51,0.00,14949.45,0.00,1009863.96,1009863.96,26143,0.0,0.0
AIRPORT SAFETY OFFICER,639160,2664533.32,201076.71,118360.54,0.00,2983970.57,2983970.57,80440,0.0,0.0
ANESTHETIST,365285,2603471.10,51471.78,151688.63,0.00,2806631.51,2806631.51,50275,0.0,0.0
ANIMAL CARE ASSISTANT SUPERVISOR,22447,55018.51,0.00,1280.11,0.00,56298.62,56298.62,2011,0.0,0.0
ANIMAL CARE ATTENDANT,355431,581173.65,17895.26,13861.22,0.00,612930.13,612930.13,28154,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
Wastewater Control Inspector,2293094,1932856.41,69299.44,16045.92,725797.58,2018201.77,2743999.35,52337,0.0,0.0
Water & Power Maint Sprv 1,747403,857242.89,73318.89,16867.84,318639.21,947429.62,1266068.83,18117,0.0,0.0
Water Conservation Admin,963430,1346892.56,0.00,22737.61,536123.88,1369630.17,1905754.05,24156,0.0,0.0
Water Const&Main Supt,349514,541548.27,109145.92,141725.22,190002.80,792419.41,982422.21,10064,0.0,0.0
Water Meter Repairer,1674767,1184714.16,27933.29,3619.48,488614.88,1216266.93,1704881.81,36234,0.0,0.0
Water Meter Shop Supervisor 1,220316,142268.43,0.00,6632.60,56926.79,148901.03,205827.82,4027,0.0,0.0
Water Operations Analyst,2891410,3494639.59,10267.56,63676.45,1150337.12,3568583.60,4718920.72,70453,0.0,0.0
Water Quality Tech III,2194446,1664188.36,41098.94,138.08,651844.23,1705425.38,2357269.61,48312,0.0,0.0
Water Quality Technician,4165097,2090246.50,87748.64,26321.69,822602.04,2204316.83,3026918.87,64448,0.0,0.0
Water QualityTech I/II,5272468,4286023.07,218157.43,21021.04,1818551.42,4525201.54,6343752.96,138866,0.0,0.0
Water Service Inspector,7124024,7077495.37,162454.00,225583.36,2648936.86,7465532.73,10114469.59,165067,0.0,0.0
Watershed Forester,497882,591507.03,0.00,8972.00,244715.01,600479.03,845194.04,12078,0.0,0.0
Watershed Keeper,7130825,4697588.12,288323.40,163081.32,2054490.75,5148992.84,7203483.59,152989,0.0,0.0
Watershed Keeper Supervisor,668344,596307.68,42539.77,35957.28,245953.23,674804.73,920757.96,16103,0.0,0.0
Watershed Worker (Seasonal),9075079,861416.98,2300.44,0.00,32425.69,863717.42,896143.11,173116,0.0,0.0
Welder,3306402,2314036.66,994602.90,102816.57,915334.93,3411456.13,4326791.06,76492,0.0,0.0
Welfare Fraud Investigator,1434316,1404490.16,0.00,0.00,486968.49,1404490.16,1891458.65,32209,0.0,0.0
Wharfinger 1,292387,152218.06,6874.27,0.00,54773.00,159092.33,213865.33,6039,0.0,0.0
Wharfinger 2,866249,735913.11,2017.69,13125.22,296189.96,751056.02,1047245.98,20129,0.0,0.0
Window Cleaner,4574904,3302669.73,951.07,79882.38,1398397.16,3383503.18,4781900.34,100648,0.0,0.0
Window Cleaner Supervisor,269521,227441.25,497.37,4598.86,93114.15,232537.48,325651.63,6039,0.0,0.0
Wire Rope Cable Maint Mechanic,2560565,1844258.02,1204820.54,317267.22,798777.25,3366345.78,4165123.03,60390,0.0,0.0
Wire Rope Cable Maint Sprv,222455,278255.24,247340.77,83505.15,117253.81,609101.16,726354.97,6039,0.0,0.0
Worker's Comp Supervisor 1,1321638,964142.15,0.00,21308.01,360307.28,985450.16,1345757.44,28183,0.0,0.0
Worker's Compensation Adjuster,6855566,5354882.63,0.00,65563.34,2077339.54,5420445.97,7497785.51,148965,0.0,0.0
X-RAY LABORATORY AIDE,585054,1239284.10,92851.81,38216.98,0.00,1370352.89,1370352.89,52286,0.0,0.0
X-Ray Laboratory Aide,9889062,4608638.71,348376.71,125378.85,1869718.05,5082394.27,6952112.32,201304,0.0,0.0
"YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS",23392,52609.91,0.00,1022.96,0.00,53632.87,53632.87,2011,0.0,0.0
Youth Comm Advisor,398711,156311.83,0.00,9345.40,74816.97,165657.23,240474.20,8052,0.0,0.0
ZOO CURATOR,18779,43148.00,0.00,23538.56,0.00,66686.56,66686.56,2011,0.0,0.0

In [82]:
salJT["JobTitle"].count()

JobTitle
ACCOUNT CLERK                                          83
ACCOUNTANT                                              5
ACCOUNTANT INTERN                                      48
ACPO,JuvP, Juv Prob (SFERS)                             1
ACUPUNCTURIST                                           1
ADMINISTRATIVE ANALYST                                 93
ADMINISTRATIVE ANALYST II                               2
ADMINISTRATIVE ANALYST III                              2
ADMINISTRATIVE ENGINEER                                10
ADMINISTRATIVE SERVICES MANAGER                         3
ADMINISTRATOR, SFGH MEDICAL CENTER                      1
AFFIRMATIVE ACTION SPECIALIST                           6
AGRICULTURAL INSPECTOR                                  2
AIRPORT ASSISTANT DEPUTY DIRECTOR, BUSINESS ADMINI      1
AIRPORT ASSISTANT DEPUTY DIRECTOR, OPERATIONS           1
AIRPORT COMMUNICATIONS OPERATOR                        27
AIRPORT COMMUNICATIONS SUPERVISOR                       2
AIRPORT ECONOMIC PLANNER                               13
AIRPORT ELECTRICIAN                                    17
AIRPORT ELECTRICIAN SUPERVISOR                          2
AIRPORT EMERGENCY PLANNING COORDINATOR                  2
AIRPORT MECHANICAL MAINTENANCE SUPERVISOR               1
AIRPORT NOISE ABATEMENT SPECIALIST                      2
AIRPORT OPERATIONS SUPERVISOR                          12
AIRPORT POLICE SERVICES AIDE                          187
AIRPORT PROPERTY SPECIALIST I                          13
AIRPORT SAFETY OFFICER                                 40
ANESTHETIST                                            25
ANIMAL CARE ASSISTANT SUPERVISOR                        1
ANIMAL CARE ATTENDANT                                  14
                                                     ...
Wastewater Control Inspector                           26
Water & Power Maint Sprv 1                              9
Water Conservation Admin                               12
Water Const&Main Supt                                   5
Water Meter Repairer                                   18
Water Meter Shop Supervisor 1                           2
Water Operations Analyst                               35
Water Quality Tech III                                 24
Water Quality Technician                               32
Water QualityTech I/II                                 69
Water Service Inspector                                82
Watershed Forester                                      6
Watershed Keeper                                       76
Watershed Keeper Supervisor                             8
Watershed Worker (Seasonal)                            86
Welder                                                 38
Welfare Fraud Investigator                             16
Wharfinger 1                                            3
Wharfinger 2                                           10
Window Cleaner                                         50
Window Cleaner Supervisor                               3
Wire Rope Cable Maint Mechanic                         30
Wire Rope Cable Maint Sprv                              3
Worker's Comp Supervisor 1                             14
Worker's Compensation Adjuster                         74
X-RAY LABORATORY AIDE                                  26
X-Ray Laboratory Aide                                 100
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS          1
Youth Comm Advisor                                      4
ZOO CURATOR                                             1
Name: JobTitle, Length: 2159, dtype: int64

In [85]:
salJT.sum().count()["Id"]

2159

2159

** What are the top 5 most common jobs? **

In [94]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
Id                  148654 non-null int64
EmployeeName        148654 non-null object
JobTitle            148654 non-null object
BasePay             148045 non-null float64
OvertimePay         148650 non-null float64
OtherPay            148650 non-null float64
Benefits            112491 non-null float64
TotalPay            148654 non-null float64
TotalPayBenefits    148654 non-null float64
Year                148654 non-null int64
Notes               0 non-null float64
Agency              148654 non-null object
Status              0 non-null float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

In [120]:
sal.groupby("JobTitle").count().loc["Special Nurse"]

Id                  4389
EmployeeName        4389
BasePay             4382
OvertimePay         4389
OtherPay            4389
Benefits            4389
TotalPay            4389
TotalPayBenefits    4389
Year                4389
Notes                  0
Agency              4389
Status                 0
Name: Special Nurse, dtype: int64

In [133]:
sal.groupby("JobTitle").size().sort_values(ascending=False).head()

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
dtype: int64

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

** How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **

In [190]:
(sal.groupby("JobTitle").size().sort_values()==1).sum()

239

In [211]:
# filter first using loc
# then groupby
# then reduce
(sal.loc[sal["Year"]==2013].groupby("JobTitle").size().sort_values()==1).sum()

202

202

** How many people have the word Chief in their job title? (This is pretty tricky) **

In [238]:
import re
sal[sal["JobTitle"].str.contains('Chief')==True]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
36160,36161,Gregory Suhr,Chief of Police,302578.00,0.00,18974.11,69810.19,321552.11,391362.30,2012,NaN,San Francisco,NaN
36162,36163,Joanne Hayes-White,"Chief, Fire Department",296943.01,0.00,17816.59,72047.88,314759.60,386807.48,2012,NaN,San Francisco,NaN
36169,36170,Brendan Ward,"Battlion Chief, Fire Suppressi",174822.47,118215.58,28845.78,49648.09,321883.83,371531.92,2012,NaN,San Francisco,NaN
36170,36171,Samson Lai,"Battlion Chief, Fire Suppressi",174822.44,112731.28,28660.28,53249.56,316214.00,369463.56,2012,NaN,San Francisco,NaN
36171,36172,Rudy Castellanos,"Battlion Chief, Fire Suppressi",176771.74,124413.13,15803.39,52320.90,316988.26,369309.16,2012,NaN,San Francisco,NaN
36172,36173,Marty Ross,"Battlion Chief, Fire Suppressi",174822.41,99623.51,36522.39,55353.92,310968.31,366322.23,2012,NaN,San Francisco,NaN
36173,36174,Mark Kearney,Assistant Deputy Chief 2,124573.50,22599.60,180516.68,32381.00,327689.78,360070.78,2012,NaN,San Francisco,NaN
36179,36180,Michael Morris,Assistant Deputy Chief 2,223371.00,7415.52,63426.03,56202.98,294212.55,350415.53,2012,NaN,San Francisco,NaN
36181,36182,James Dudley,Deputy Chief 3,263426.50,0.00,22857.87,59265.59,286284.37,345549.96,2012,NaN,San Francisco,NaN
36190,36191,Thomas Harvey,Assistant Deputy Chief 2,226475.05,0.00,54967.53,55722.16,281442.58,337164.74,2012,NaN,San Francisco,NaN
36196,36197,David Shinn,Deputy Chief 3,263426.50,0.00,12320.80,57576.73,275747.30,333324.03,2012,NaN,San Francisco,NaN
36197,36198,Kevin Cashman,Deputy Chief 3,253094.51,0.00,22206.40,56561.05,275300.91,331861.96,2012,NaN,San Francisco,NaN
36201,36202,Pete Fay Jr,"Battlion Chief, Fire Suppressi",176515.48,74246.62,23772.00,53207.72,274534.10,327741.82,2012,NaN,San Francisco,NaN
36204,36205,Denise Schmitt,Deputy Chief 3,263390.60,0.00,819.01,60298.97,264209.61,324508.58,2012,NaN,San Francisco,NaN
36208,36209,Kevin Taylor,"Battlion Chief, Fire Suppressi",176515.48,71643.89,23352.06,47455.23,271511.43,318966.66,2012,NaN,San Francisco,NaN
36212,36213,Kirk Richardson,"Battlion Chief, Fire Suppressi",174822.50,67875.53,21516.98,52568.73,264215.01,316783.74,2012,NaN,San Francisco,NaN
36215,36216,Lorrie Kalos,"Battlion Chief, Fire Suppressi",174822.48,63116.25,24255.85,52687.80,262194.58,314882.38,2012,NaN,San Francisco,NaN
36220,36221,James Vannucchi,"Battlion Chief, Fire Suppressi",174822.43,53465.15,30760.78,49888.38,259048.36,308936.74,2012,NaN,San Francisco,NaN
36222,36223,Bryan Rubenstein,"Battlion Chief, Fire Suppressi",174822.44,58091.97,23603.24,52059.82,256517.65,308577.47,2012,NaN,San Francisco,NaN
36226,36227,Michael Thompson,"Battlion Chief, Fire Suppressi",176515.52,54339.84,22064.50,52776.95,252919.86,305696.81,2012,NaN,San Francisco,NaN
36228,36229,Kevin Smith,"Battlion Chief, Fire Suppressi",176515.52,45860.99,27969.77,53182.45,250346.28,303528.73,2012,NaN,San Francisco,NaN
36230,36231,Rex Hale,"Battlion Chief, Fire Suppressi",176515.49,49002.61,24503.36,52693.66,250021.46,302715.12,2012,NaN,San Francisco,NaN
36233,36234,Jose Velo,Assistant Deputy Chief 2,226475.02,0.00,16877.44,58449.76,243352.46,301802.22,2012,NaN,San Francisco,NaN
36241,36242,Jeffrey Myers,Emergency Medical Svcs Chief,226475.00,0.00,13588.50,57982.22,240063.50,298045.72,2012,NaN,San Francisco,NaN
36247,36248,Lyn Tomioka,Deputy Chief 3,234405.50,0.00,5884.63,55870.50,240290.13,296160.63,2012,NaN,San Francisco,NaN
36248,36249,George Garcia,"Battlion Chief, Fire Suppressi",144510.79,76624.10,32650.42,42316.01,253785.31,296101.32,2012,NaN,San Francisco,NaN
36250,36251,Michael Bryant,"Battlion Chief, Fire Suppressi",176515.50,41747.56,24263.24,52962.59,242526.30,295488.89,2012,NaN,San Francisco,NaN
36256,36257,Michael Biel,Deputy Chief 3,221828.00,0.00,19194.10,52217.79,241022.10,293239.89,2012,NaN,San Francisco,NaN
36259,36260,Charles Crane,"Battlion Chief, Fire Suppressi",176515.51,51949.05,13581.09,50933.68,242045.65,292979.33,2012,NaN,San Francisco,NaN
36263,36264,Mark Johnson,"Battlion Chief, Fire Suppressi",174822.43,39792.60,22624.05,51764.36,237239.08,289003.44,2012,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120012,120013,Mark A Naddy,Chief Stationary Engineer,99736.06,450.62,5934.48,36955.12,106121.16,143076.28,2014,NaN,San Francisco,NaN
121045,121046,Rolando C Lopez,Chief Stationary Engineer,91172.93,5517.86,5300.90,34959.56,101991.69,136951.25,2014,NaN,San Francisco,NaN
122123,122124,Nerivaldo C Santos,Chief Fire Alarm Dispatcher,90665.02,7235.84,70.00,33692.92,97970.86,131663.78,2014,NaN,San Francisco,NaN
122170,122171,James M Ryan,Chief Surveyor,95288.05,396.83,0.00,35673.70,95684.88,131358.58,2014,NaN,San Francisco,NaN
122574,122575,Loretta M Cecconi,Chief Dietitian,94694.30,0.00,200.00,34558.44,94894.30,129452.74,2014,NaN,San Francisco,NaN
123030,123031,Michael G Gay,Chief Stationary Engineer,81476.01,5806.87,17427.93,22612.24,104710.81,127323.05,2014,NaN,San Francisco,NaN
124548,124549,Paul H Mabry,Chief Surveyor,88421.29,0.00,0.00,31060.87,88421.29,119482.16,2014,NaN,San Francisco,NaN
124647,124648,Mark Y Antonio,Chief Clerk,82230.07,0.00,3397.31,33432.00,85627.38,119059.38,2014,NaN,San Francisco,NaN
125497,125498,Artie L L Kelly,Chief Clerk,82230.01,0.00,1156.44,32076.41,83386.45,115462.86,2014,NaN,San Francisco,NaN
125525,125526,Tuti I Suardana,Chief Clerk,82230.03,0.00,1040.00,32063.05,83270.03,115333.08,2014,NaN,San Francisco,NaN
125670,125671,Sylvia N Thai,Chief Clerk,82230.04,0.00,624.00,31970.56,82854.04,114824.60,2014,NaN,San Francisco,NaN
125673,125674,Deborah L Brown,Chief Clerk,82230.01,0.00,624.00,31970.56,82854.01,114824.57,2014,NaN,San Francisco,NaN
125861,125862,Cuong Quach,Chief Clerk,82299.89,0.00,0.00,31861.18,82299.89,114161.07,2014,NaN,San Francisco,NaN
125893,125894,Peter Aviles,Chief Clerk,82230.02,0.00,0.00,31834.29,82230.02,114064.31,2014,NaN,San Francisco,NaN
125907,125908,Shahin P Shaikh,Chief Clerk,82195.25,0.00,0.00,31820.96,82195.25,114016.21,2014,NaN,San Francisco,NaN
126041,126042,Donald P Margolis,Assistant Chief Attorney 1,62720.01,0.00,33084.71,17560.74,95804.72,113365.46,2014,NaN,San Francisco,NaN
127965,127966,Sylvia M Selinger,Chief Clerk,75606.53,0.00,0.00,31027.57,75606.53,106634.10,2014,NaN,San Francisco,NaN
128030,128031,Janice Gragasin,Chief Clerk,75968.03,0.00,0.00,30478.04,75968.03,106446.07,2014,NaN,San Francisco,NaN
131266,131267,Cheryl L Coleman,Chief Clerk,68089.84,0.00,40.00,26349.83,68129.84,94479.67,2014,NaN,San Francisco,NaN
131377,131378,Ann M Castillo,Chief Telephone Operator,65117.43,0.00,624.60,28244.66,65742.03,93986.69,2014,NaN,San Francisco,NaN
132799,132800,Judith A Boyajian,Assistant Chief Attorney 1,88352.39,0.00,575.00,0.00,88927.39,88927.39,2014,NaN,San Francisco,NaN
133842,133843,Jennifer L Novak,Chief Clerk,61327.71,0.00,696.96,23793.25,62024.67,85817.92,2014,NaN,San Francisco,NaN
137010,137011,Ryan L Butterfield,Chief Preparator,46950.77,0.00,0.00,20659.10,46950.77,67609.87,2014,NaN,San Francisco,NaN
137168,137169,Tony E Durkee,Chief Surveyor,65432.94,0.00,0.00,654.38,65432.94,66087.32,2014,NaN,San Francisco,NaN
137553,137554,Paula Jesson,Assistant Chief Attorney 1,62095.32,0.00,431.25,0.00,62526.57,62526.57,2014,NaN,San Francisco,NaN
138011,138012,Sharon C Jackson,Chief Deputy Adlt Probation Of,56660.18,0.00,0.00,566.61,56660.18,57226.79,2014,NaN,San Francisco,NaN
139620,139621,Anita S Lee,Chief Clerk,38598.86,0.00,0.00,386.00,38598.86,38984.86,2014,NaN,San Francisco,NaN
139709,139710,George D Vaughan,Chief Nursery Specialist,27319.47,483.90,0.00,10334.67,27803.37,38138.04,2014,NaN,San Francisco,NaN
140080,140081,Patrick W Gillespie,Chief Preparator,24091.00,0.00,0.00,10176.77,24091.00,34267.77,2014,NaN,San Francisco,NaN
140156,140157,Christopher L Ochoa,Chief Stationary Engineer,24392.00,418.71,0.00,8918.44,24810.71,33729.15,2014,NaN,San Francisco,NaN

In [246]:
sal[sal["JobTitle"].str.contains('^Chief*',case=True,regex=True)==True]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
36160,36161,Gregory Suhr,Chief of Police,302578.00,0.00,18974.11,69810.19,321552.11,391362.30,2012,NaN,San Francisco,NaN
36162,36163,Joanne Hayes-White,"Chief, Fire Department",296943.01,0.00,17816.59,72047.88,314759.60,386807.48,2012,NaN,San Francisco,NaN
36345,36346,Burk Delventhal,Chief Atty1 (Civil & Criminal),206752.00,0.00,312.50,64406.22,207064.50,271470.72,2012,NaN,San Francisco,NaN
36419,36420,Joanne Hoeper,Chief Atty1 (Civil & Criminal),201384.40,0.00,312.50,60796.93,201696.90,262493.83,2012,NaN,San Francisco,NaN
36420,36421,Wendy Still,Chief Adult Probation Officer,192454.46,0.00,5185.04,64849.52,197639.50,262489.02,2012,NaN,San Francisco,NaN
36817,36818,Freya Horne,Chief Atty1 (Civil & Criminal),180477.02,0.00,312.50,57295.83,180789.52,238085.35,2012,NaN,San Francisco,NaN
36881,36882,Matthew Gonzalez,Chief Atty1 (Civil & Criminal),180022.76,0.00,312.50,55815.36,180335.26,236150.62,2012,NaN,San Francisco,NaN
36888,36889,James Harrigan,Chief Atty1 (Civil & Criminal),15158.50,0.00,206752.00,14074.28,221910.50,235984.78,2012,NaN,San Francisco,NaN
37011,37012,Albert Waters II,Chief Deputy Sheriff,156308.01,9857.01,14917.66,49908.78,181082.68,230991.46,2012,NaN,San Francisco,NaN
37433,37434,Matthew Freeman,Chief Deputy Sheriff,153008.00,5298.13,11560.03,51399.35,169866.16,221265.51,2012,NaN,San Francisco,NaN
37701,37702,Perry Bonelli,Chief Stationary Engineer,93652.00,66974.96,11310.42,42331.10,171937.38,214268.48,2012,NaN,San Francisco,NaN
38099,38100,Katherine Johnson,Chief Deputy Sheriff,142338.06,2868.98,12237.05,48803.86,157444.09,206247.95,2012,NaN,San Francisco,NaN
39025,39026,Kenneth Payne,Chief Water Service Inspector,117259.07,9893.24,19385.30,45415.98,146537.61,191953.59,2012,NaN,San Francisco,NaN
39270,39271,Gregory Chase,Chief Stationary Engineer,93652.00,19998.50,32462.72,42858.10,146113.22,188971.32,2012,NaN,San Francisco,NaN
39867,39868,Daniel Lowrey,Chief Building Inspector,128738.70,0.00,6436.31,47011.15,135175.01,182186.16,2012,NaN,San Francisco,NaN
40244,40245,Steven Panelli,Chief Plumbing Inspector,125552.23,0.00,6278.88,46483.04,131831.11,178314.15,2012,NaN,San Francisco,NaN
40290,40291,John Aires,Chief Building Inspector,125119.76,0.00,6256.03,46555.17,131375.79,177930.96,2012,NaN,San Francisco,NaN
40444,40445,Neil Friedman,Chief Building Inspector,124563.63,0.00,6227.22,45961.95,130790.85,176752.80,2012,NaN,San Francisco,NaN
40479,40480,Leo Martinez,Chief Stationary Engineer,106754.18,15634.46,10458.13,43682.28,132846.77,176529.05,2012,NaN,San Francisco,NaN
40834,40835,Michael Weisenberger,Chief Water Service Inspector,118429.32,648.17,8786.99,45238.35,127864.48,173102.83,2012,NaN,San Francisco,NaN
40904,40905,Ron Allen,Chief Electrical Inspector,125057.92,0.00,2205.31,45276.29,127263.23,172539.52,2012,NaN,San Francisco,NaN
41344,41345,Eric Kondo,Chief Stationary Engineer,93652.07,24518.73,9641.58,41230.17,127812.38,169042.55,2012,NaN,San Francisco,NaN
42128,42129,Rosemary Bosque,Chief Housing Inspector,120073.35,0.00,0.00,43808.73,120073.35,163882.08,2012,NaN,San Francisco,NaN
42243,42244,Martin Krizay,Chief Dep Adlt Prob Of (SFERS),121161.81,0.00,1500.00,40521.91,122661.81,163183.72,2012,NaN,San Francisco,NaN
42531,42532,Nerivaldo Santos,Chief Fire Alarm Dispatcher,85360.00,30242.50,6715.52,39092.88,122318.02,161410.90,2012,NaN,San Francisco,NaN
42557,42558,Robert Peterson,Chief Surveyor,115635.04,0.00,1750.00,43815.33,117385.04,161200.37,2012,NaN,San Francisco,NaN
42608,42609,Michael Gay,Chief Stationary Engineer,93652.30,27689.40,0.00,39523.15,121341.70,160864.85,2012,NaN,San Francisco,NaN
42625,42626,Arturo Lopez,Chief Water Service Inspector,116790.96,1009.33,0.00,42947.18,117800.29,160747.47,2012,NaN,San Francisco,NaN
42775,42776,Robert Hanley,Chief Surveyor,115635.00,0.00,0.00,44080.97,115635.00,159715.97,2012,NaN,San Francisco,NaN
42886,42887,Marilyn Lopes,Chief Surveyor,115635.01,0.00,0.00,43390.80,115635.01,159025.81,2012,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119677,119678,Ko Ko Zin,Chief Stationary Engineer,98799.82,2272.97,7255.47,37052.60,108328.26,145380.86,2014,NaN,San Francisco,NaN
119999,120000,Rosemary V Bosque,Chief Housing Inspector,108731.63,0.00,0.00,34447.87,108731.63,143179.50,2014,NaN,San Francisco,NaN
120005,120006,Viktor Kirienko,Chief Stationary Engineer,99736.05,503.15,5934.56,36955.11,106173.76,143128.87,2014,NaN,San Francisco,NaN
120012,120013,Mark A Naddy,Chief Stationary Engineer,99736.06,450.62,5934.48,36955.12,106121.16,143076.28,2014,NaN,San Francisco,NaN
121045,121046,Rolando C Lopez,Chief Stationary Engineer,91172.93,5517.86,5300.90,34959.56,101991.69,136951.25,2014,NaN,San Francisco,NaN
122123,122124,Nerivaldo C Santos,Chief Fire Alarm Dispatcher,90665.02,7235.84,70.00,33692.92,97970.86,131663.78,2014,NaN,San Francisco,NaN
122170,122171,James M Ryan,Chief Surveyor,95288.05,396.83,0.00,35673.70,95684.88,131358.58,2014,NaN,San Francisco,NaN
122574,122575,Loretta M Cecconi,Chief Dietitian,94694.30,0.00,200.00,34558.44,94894.30,129452.74,2014,NaN,San Francisco,NaN
123030,123031,Michael G Gay,Chief Stationary Engineer,81476.01,5806.87,17427.93,22612.24,104710.81,127323.05,2014,NaN,San Francisco,NaN
124548,124549,Paul H Mabry,Chief Surveyor,88421.29,0.00,0.00,31060.87,88421.29,119482.16,2014,NaN,San Francisco,NaN
124647,124648,Mark Y Antonio,Chief Clerk,82230.07,0.00,3397.31,33432.00,85627.38,119059.38,2014,NaN,San Francisco,NaN
125497,125498,Artie L L Kelly,Chief Clerk,82230.01,0.00,1156.44,32076.41,83386.45,115462.86,2014,NaN,San Francisco,NaN
125525,125526,Tuti I Suardana,Chief Clerk,82230.03,0.00,1040.00,32063.05,83270.03,115333.08,2014,NaN,San Francisco,NaN
125670,125671,Sylvia N Thai,Chief Clerk,82230.04,0.00,624.00,31970.56,82854.04,114824.60,2014,NaN,San Francisco,NaN
125673,125674,Deborah L Brown,Chief Clerk,82230.01,0.00,624.00,31970.56,82854.01,114824.57,2014,NaN,San Francisco,NaN
125861,125862,Cuong Quach,Chief Clerk,82299.89,0.00,0.00,31861.18,82299.89,114161.07,2014,NaN,San Francisco,NaN
125893,125894,Peter Aviles,Chief Clerk,82230.02,0.00,0.00,31834.29,82230.02,114064.31,2014,NaN,San Francisco,NaN
125907,125908,Shahin P Shaikh,Chief Clerk,82195.25,0.00,0.00,31820.96,82195.25,114016.21,2014,NaN,San Francisco,NaN
127965,127966,Sylvia M Selinger,Chief Clerk,75606.53,0.00,0.00,31027.57,75606.53,106634.10,2014,NaN,San Francisco,NaN
128030,128031,Janice Gragasin,Chief Clerk,75968.03,0.00,0.00,30478.04,75968.03,106446.07,2014,NaN,San Francisco,NaN
131266,131267,Cheryl L Coleman,Chief Clerk,68089.84,0.00,40.00,26349.83,68129.84,94479.67,2014,NaN,San Francisco,NaN
131377,131378,Ann M Castillo,Chief Telephone Operator,65117.43,0.00,624.60,28244.66,65742.03,93986.69,2014,NaN,San Francisco,NaN
133842,133843,Jennifer L Novak,Chief Clerk,61327.71,0.00,696.96,23793.25,62024.67,85817.92,2014,NaN,San Francisco,NaN
137010,137011,Ryan L Butterfield,Chief Preparator,46950.77,0.00,0.00,20659.10,46950.77,67609.87,2014,NaN,San Francisco,NaN
137168,137169,Tony E Durkee,Chief Surveyor,65432.94,0.00,0.00,654.38,65432.94,66087.32,2014,NaN,San Francisco,NaN
138011,138012,Sharon C Jackson,Chief Deputy Adlt Probation Of,56660.18,0.00,0.00,566.61,56660.18,57226.79,2014,NaN,San Francisco,NaN
139620,139621,Anita S Lee,Chief Clerk,38598.86,0.00,0.00,386.00,38598.86,38984.86,2014,NaN,San Francisco,NaN
139709,139710,George D Vaughan,Chief Nursery Specialist,27319.47,483.90,0.00,10334.67,27803.37,38138.04,2014,NaN,San Francisco,NaN
140080,140081,Patrick W Gillespie,Chief Preparator,24091.00,0.00,0.00,10176.77,24091.00,34267.77,2014,NaN,San Francisco,NaN
140156,140157,Christopher L Ochoa,Chief Stationary Engineer,24392.00,418.71,0.00,8918.44,24810.71,33729.15,2014,NaN,San Francisco,NaN

In [272]:
sal[sal["JobTitle"].str.contains('Chief|chief|CHIEF',case=True,regex=True)==True]["Id"].count()

627

In [270]:
sal[sal["JobTitle"].str.match('Chief',case=True)==True]["Id"].count()

198

477

** Bonus: Is there a correlation between length of the Job Title string and Salary? **

In [263]:
sal.corr()

,Id,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Status
Id,1.000000,-0.204878,-0.081505,-0.100403,-0.348957,-0.211478,-0.092190,0.968171,NaN,NaN
BasePay,-0.204878,1.000000,0.266740,0.285655,0.918028,0.954494,0.946595,0.033751,NaN,NaN
OvertimePay,-0.081505,0.266740,1.000000,0.316592,0.301207,0.504859,0.467981,0.027887,NaN,NaN
OtherPay,-0.100403,0.285655,0.316592,1.000000,0.233178,0.470496,0.422341,-0.002499,NaN,NaN
Benefits,-0.348957,0.918028,0.301207,0.233178,1.000000,0.884097,0.930140,-0.043136,NaN,NaN
TotalPay,-0.211478,0.954494,0.504859,0.470496,0.884097,1.000000,0.977313,0.032090,NaN,NaN
TotalPayBenefits,-0.092190,0.946595,0.467981,0.422341,0.930140,0.977313,1.000000,0.151947,NaN,NaN
Year,0.968171,0.033751,0.027887,-0.002499,-0.043136,0.032090,0.151947,1.000000,NaN,NaN
Notes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Status,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [265]:
sal['titleLen']=sal["JobTitle"].str.len()

In [266]:
sal["titleLen"].corr(sal["TotalPayBenefits"])

-0.03687844593260676

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000

# Great Job!